### ISSUE TITLE
在ACG板块排版错误

### ISSUE THREAD

**Issue by gyli** [zdhxiong/v2ex-material-theme#6]
包括板块页面和其中的帖子页面，Rightbar出现在了错误位置
<img width="946" alt="Screen Shot 2019-10-24 at 11 56 30 AM" src="https://user-images.githubusercontent.com/2060045/67516448-870dea80-f655-11e9-94d0-95372011c15d.png">

**Comment by zdhxiong** [comment]
我这儿显示没有问题，你可以调试下样式，看看是什么原因。

**Comment by gyli** [comment]
抱歉忘贴URL了，因为和板块的CSS设置有关
https://www.v2ex.com/go/acg
这个板块我在没有插件的 Chrome 下复现了

具体是由于其中的CSS
```
.box {
   background-color: rgba(255, 255, 255, 0.9);
  -webkit-backdrop-filter: blur(15px);
  backdrop-filter: blur(15px);
}

```

**Comment by zdhxiong** [comment]
我依然无法复现，另外我在这个页面找到的额外的 CSS 和你的不一样，我的是：
```css
.box {
  opacity: 0.95;
  -webkit-backdrop-filter: blur(15px);
  backdrop-filter: blur(15px);
}
```
